### PR TITLE
 UI Changed and Neon colors & smooth Scrolling effect added

### PR DESCRIPTION
**Pull request by sapsa07**
Done

### CODE REVIEW

**Comment by sapsa07** [comment]
Let me Know any other changes required

**Comment by PatilShreyas** [comment]
Can you please enable GitHub pages in your repo so that I can check ?

**Comment by sapsa07** [comment]
I dont have any github pages ... plz clone it and let me know if any more things required.

**Comment by PatilShreyas** [comment]
Thanks for your contribution @sapsa07. The experiment was amazing but it's not going to deploy.

**Pull request closed without merging**
