### PR TITLE
Fix span at words wrapper

### PR DESCRIPTION
**Pull request by Abg4real**
Changed the width of span at words wrapper.
Before: 
before2
After:
before

### CODE REVIEW

**Comment by PatilShreyas** [comment]
@Abg4real This is working fine even without this change. Can't find this issue

**Comment by goforbg** [comment]
@PatilShreyas I think you should try it on a different device, at first I thought the person was making the PR just for hacktoberfest but I am able to replicate it too.

**Comment by PatilShreyas** [comment]
I tested it on my mobile. It's still cropping that word

**Comment by PatilShreyas** [comment]
@Abg4real See 
image

**Comment by Abg4real** [comment]
I guess this might be happening due to different view port sizes.
In the latest commit I changed the padding class of about me text container to better suit the smaller screens.

**Comment by Abg4real** [comment]
This is the updated commit. The dynamic width was being added via js.
Adding a fixed width seems to fix the issue in all view ports.

**Comment by Abg4real** [comment]
Here are some screen shots.
PS: The full size screen shot has a resolution of 1366 x 768px.
Annotation 2020-10-02 201517
Annotation 2020-10-02 201540
Updated changes

**Review by PatilShreyas — APPROVED** [review]
Nice. It looks good now 👍🏻

**Pull request merged**
